# Models are generated by `inspectdb` into models_generated.py (all managed = False,
# mapped to the existing Aiven tables). Regenerate that file if the schema changes.
from .models_generated import *  # noqa: F401,F403
